import math

RES = WIDTH, HEIGHT = 1024, 600
#RES = WIDTH, HEIGHT = 960, 960
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
FPS = 13

PLAYER_ANGLE = 0
PLAYER_SPEED = 0.05
LOOK_SENSITIVITY = 0.05
PLAYER_SIZE_SCALE = 100
PLAYER_MAX_HEALTH = 100
PLAYER_DAMAGE = 50
PLAYER_STARTING_AMMO = 16

FLOOR_COLOR = (136, 168, 200)

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 32

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2